In [1]:
!python -m pip install -U python-woc pandas matplotlib
# please clear the output of this cell in your notebook before checking it in

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: python-woc in /home/wch356/.local/lib/python3.9/site-packages (0.4.1)
Requirement already satisfied: pandas in /home/wch356/.local/lib/python3.9/site-packages (2.3.3)
Requirement already satisfied: matplotlib in /home/wch356/.local/lib/python3.9/site-packages (3.9.4)
Requirement already satisfied: python-lzf<0.3.0,>=0.2.4 in /home/wch356/.local/lib/python3.9/site-packages (from python-woc) (0.2.6)
Requirement already satisfied: rapidgzip<0.15.0,>=0.14.3 in /home/wch356/.local/lib/python3.9/site-packages (from python-woc) (0.14.5)
Requirement already satisfied: tqdm<5.0.0,>=4.65.0 in /home/wch356/.local/lib/python3.9/site-packages (from python-woc) (4.70.1)
Requirement already satisfied: chardet<6.0.0,>=5.2.0 in /home/wch356/.local/lib/python3.9/site-packages (from python-woc) (5.2.0)
Requirement already satisfied: httpx<0.29.0,>=0.28.1 in /home/wch356/.local/lib/python3.9/site-packages (from python-woc) (0.28.1)
Requirement already satisfied: tzdata>=2022.7 in /home/wch356/.local/lib/python3.9/site-packages (from pandas) (2026.4)
Requirement already satisfied: pytz>=2020.1 in /usr/lib/python3.9/site-packages (from pandas) (2021.1)
Requirement already satisfied: numpy>=1.22.4 in /usr/lib64/python3.9/site-packages (from pandas) (1.23.5)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/lib/python3.9/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: importlib-resources>=3.2.0 in /home/wch356/.local/lib/python3.9/site-packages (from matplotlib) (6.5.2)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/lib64/python3.9/site-packages (from matplotlib) (1.4.1)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/lib/python3.9/site-packages (from matplotlib) (2.4.7)
Requirement already satisfied: contourpy>=1.0.1 in /home/wch356/.local/lib/python3.9/site-packages (from matplotlib) (1.3.0)
Requirement already satisfied: fonttools>=4.22.0 in /home/wch356/.local/lib/python3.9/site-packages (from matplotlib) (4.60.2)
Requirement already satisfied: cycler>=0.10 in /usr/lib/python3.9/site-packages (from matplotlib) (0.11.0)
Requirement already satisfied: packaging>=20.0 in /usr/lib/python3.9/site-packages (from matplotlib) (20.9)
Requirement already satisfied: pillow>=8 in /usr/lib64/python3.9/site-packages (from matplotlib) (10.0.1)
Requirement already satisfied: httpcore==1.* in /home/wch356/.local/lib/python3.9/site-packages (from httpx<0.29.0,>=0.28.1->python-woc) (1.0.9)
Requirement already satisfied: idna in /usr/lib/python3.9/site-packages (from httpx<0.29.0,>=0.28.1->python-woc) (2.10)
Requirement already satisfied: anyio in /home/wch356/.local/lib/python3.9/site-packages (from httpx<0.29.0,>=0.28.1->python-woc) (4.12.1)
Requirement already satisfied: certifi in /home/wch356/.local/lib/python3.9/site-packages (from httpx<0.29.0,>=0.28.1->python-woc) (2026.7.22)
Requirement already satisfied: h11>=0.16 in /home/wch356/.local/lib/python3.9/site-packages (from httpcore==1.*->httpx<0.29.0,>=0.28.1->python-woc) (0.16.0)
Requirement already satisfied: zipp>=3.1.0 in /usr/local/lib/python3.9/site-packages (from importlib-resources>=3.2.0->matplotlib) (3.23.0)
Requirement already satisfied: six>=1.5 in /usr/lib/python3.9/site-packages (from python-dateutil>=2.8.2->pandas) (1.15.0)
Requirement already satisfied: typing_extensions>=4.5 in /usr/local/lib/python3.9/site-packages (from anyio->httpx<0.29.0,>=0.28.1->python-woc) (4.14.1)
Requirement already satisfied: exceptiongroup>=1.0.2 in /usr/local/lib/python3.9/site-packages (from anyio->httpx<0.29.0,>=0.28.1->python-woc) (1.3.0)

In [2]:
from woc.remote import WocMapsRemote
from tqdm import tqdm
import pandas as pd
# creates the client
woc = WocMapsRemote( base_url="https://worldofcode.org/api/")
# if you got an API key
# woc = WocMapsRemote( base_url="https://worldofcode.org/api/", api_key="woc-XXXXXX-YYYYYY" )

# Now for each of the ten projects you were assigned get commits, e.g.
projects = [
    'kristofferc_pgfplotsx.jl',
    'fizban007_coffeegpu',
    'clayne_retrowrite',
    'dkazanc_tomophantom',
    'alicevision_meshroom',
    'fmidev_smartmet-library-newbase',
    'knausb_vcfr',
    'fedml-ai_fedml',
    'latte-central_latte',
    'stineb_mct',
]


list_df_commits = []
for prj in projects:
  # Convert GitHub repository names to WoC V2412 project names
  prj = prj.lower().replace('/','_',2)
  commits = woc.get_values('p2c', prj)
  df = pd.DataFrame(commits, columns=["sha1"])
  df['project'] = prj
  list_df_commits.append(df)
df = pd.concat(list_df_commits)
#perhaps save the list (if no errors) so you do not need to retrieve them again
df.to_csv('df_commits.csv')
df.head(1)

                                       sha1                   project
0  00103d05f1291a1acf567cbd3f18cb60355096de  kristofferc_pgfplotsx.jl

In [3]:
# If the number of commits its not very large, you can try to get them all at the same time,
# The max batch size is 10
import time
# let us first split df['sha1'] in chunks
chunks = [df['sha1'][x:x+10] for x in range(0, len(df), 10)]
commit_data = []

for chunk in tqdm(chunks): # iterate over the commits
  # res, err = woc.show_content_many('commit',chunk.to_list())

  # commit.tch returns the same data but faster
  res, err = woc.get_values_many('commit.tch',chunk.to_list())
  res = {k: v[0] for k, v in res.items()}  # this conversion is necessary because of the internal implementation

  # to walk around the rate limit
  time.sleep(1)

  if err: # check for errors
    print('Got Errors', err)

  for commit_sha, commit in res.items():
    # flatten commit objects
    commit_data.append({
          'commit': commit_sha,
          'tree': commit[0],
          'parent': list(commit[1]),
          'author': commit[2][0],
          'author_time': int(commit[2][1]),
          'author_tz': commit[2][2],
          'committer': commit[3][0],
          'committer_time': int(commit[3][1]),
          'committer_tz': commit[3][2],
          'message': commit[4],
    })

df_commit_data = pd.DataFrame(commit_data)
df_commit_data = df_commit_data.merge(df, left_on='commit', right_on='sha1')
df_commit_data.to_csv('df_commit_data.csv', index=False)
df_commit_data.head(2)

  1%|█                                                                             | 50/3606 [00:51<1:00:44,  1.02s/it]

Got Errors {'7342aa2ba051597afdfd2863b474012ea36f8f1f': 'Key 7342aa2ba051597afdfd2863b474012ea36f8f1f not found in /da5_fast/All.sha1c/commit_115.tch'}

  2%|█▎                                                                            | 61/3606 [01:02<1:00:34,  1.03s/it]

Got Errors {'86cd1e530fc4a311c0679b186facec1e49fa64e5': 'Key 86cd1e530fc4a311c0679b186facec1e49fa64e5 not found in /da5_fast/All.sha1c/commit_6.tch'}

  2%|█▋                                                                            | 76/3606 [01:18<1:00:15,  1.02s/it]

Got Errors {'a9dc602f1e07cb9877a0eff14071d440efc9f5db': 'Key a9dc602f1e07cb9877a0eff14071d440efc9f5db not found in /da5_fast/All.sha1c/commit_41.tch'}

  3%|██▏                                                                             | 97/3606 [01:39<59:58,  1.03s/it]

Got Errors {'d73358097c48e2fec79935357d7f536214cd755f': 'Key d73358097c48e2fec79935357d7f536214cd755f not found in /da5_fast/All.sha1c/commit_87.tch'}

  3%|██▏                                                                             | 98/3606 [01:40<59:55,  1.03s/it]

Got Errors {'d8315cba74a456ecca2a56088e24e4797a8ea039': 'Key d8315cba74a456ecca2a56088e24e4797a8ea039 not found in /da5_fast/All.sha1c/commit_88.tch'}

  3%|██▎                                                                            | 106/3606 [01:48<59:48,  1.03s/it]

Got Errors {'e8cace5213723798eb7dfdcd5270f953a68183cb': 'Key e8cace5213723798eb7dfdcd5270f953a68183cb not found in /da5_fast/All.sha1c/commit_104.tch', 'e8d4f5f915b6fd4bc719b53e962454f7eaa13daa': 'Key e8d4f5f915b6fd4bc719b53e962454f7eaa13daa not found in /da5_fast/All.sha1c/commit_104.tch'}

  3%|██▌                                                                            | 115/3606 [01:58<59:35,  1.02s/it]

Got Errors {'fd15c1ff65f8ecd9b6dfb7eb86810669b0f608e0': 'Key fd15c1ff65f8ecd9b6dfb7eb86810669b0f608e0 not found in /da5_fast/All.sha1c/commit_125.tch'}

  7%|█████▎                                                                         | 242/3606 [04:08<57:25,  1.02s/it]

Got Errors {'725bf07481ae3ed1612c3e139569bebbdb59fc05': 'Key 725bf07481ae3ed1612c3e139569bebbdb59fc05 not found in /da5_fast/All.sha1c/commit_114.tch'}

  7%|█████▎                                                                         | 243/3606 [04:09<57:25,  1.02s/it]

Got Errors {'7783596177ff47870c65aff8bf5e9084ad3ea192': 'Key 7783596177ff47870c65aff8bf5e9084ad3ea192 not found in /da5_fast/All.sha1c/commit_119.tch'}

  7%|█████▎                                                                         | 245/3606 [04:11<57:24,  1.02s/it]

Got Errors {'819f28b3641054f415e1ec2f85ba0b639533e314': 'Key 819f28b3641054f415e1ec2f85ba0b639533e314 not found in /da5_fast/All.sha1c/commit_1.tch'}

  7%|█████▋                                                                         | 261/3606 [04:27<57:03,  1.02s/it]

Got Errors {'dc20686b33037393f174fa19e66257cb7b5abf0c': 'Key dc20686b33037393f174fa19e66257cb7b5abf0c not found in /da5_fast/All.sha1c/commit_92.tch'}

  8%|██████▏                                                                        | 281/3606 [04:48<56:44,  1.02s/it]

Got Errors {'05076b6a81bb0329d352c6521aeaddd43cf06462': 'Key 05076b6a81bb0329d352c6521aeaddd43cf06462 not found in /da5_fast/All.sha1c/commit_5.tch'}

  9%|██████▊                                                                        | 311/3606 [05:18<56:16,  1.02s/it]

Got Errors {'0f7ab2181b758b5f402002d910b82ef8f96e485d': 'Key 0f7ab2181b758b5f402002d910b82ef8f96e485d not found in /da5_fast/All.sha1c/commit_15.tch'}

  9%|███████                                                                        | 325/3606 [05:33<56:02,  1.02s/it]

Got Errors {'155412c47af171cef4a1459c397297d5195fcd0a': 'Key 155412c47af171cef4a1459c397297d5195fcd0a not found in /da5_fast/All.sha1c/commit_21.tch'}

  9%|███████▎                                                                       | 331/3606 [05:39<55:53,  1.02s/it]

Got Errors {'17993a0ab5541aa6b5a3337247d12926ecc6a217': 'Key 17993a0ab5541aa6b5a3337247d12926ecc6a217 not found in /da5_fast/All.sha1c/commit_23.tch'}

 10%|███████▌                                                                       | 345/3606 [05:53<55:42,  1.03s/it]

Got Errors {'1cb6682b17ae69bd0834610517aefcef3b8d9fe2': 'Key 1cb6682b17ae69bd0834610517aefcef3b8d9fe2 not found in /da5_fast/All.sha1c/commit_28.tch'}

 11%|████████▎                                                                      | 382/3606 [06:31<55:01,  1.02s/it]

Got Errors {'2a58a1cbc4a5694935cfd138c636c59011e28577': 'Key 2a58a1cbc4a5694935cfd138c636c59011e28577 not found in /da5_fast/All.sha1c/commit_42.tch'}

 12%|█████████▏                                                                     | 418/3606 [07:08<54:24,  1.02s/it]

Got Errors {'3788b77cb3fca4bff049e0889a18fd4b702fcaa3': 'Key 3788b77cb3fca4bff049e0889a18fd4b702fcaa3 not found in /da5_fast/All.sha1c/commit_55.tch'}

 12%|█████████▌                                                                     | 436/3606 [07:27<54:08,  1.02s/it]

Got Errors {'3eea604d26f7cc412c80fc94d3bbfef9e36e684a': 'Key 3eea604d26f7cc412c80fc94d3bbfef9e36e684a not found in /da5_fast/All.sha1c/commit_62.tch'}

 14%|██████████▊                                                                    | 496/3606 [08:28<53:04,  1.02s/it]

Got Errors {'53c34ed1d63dcc7af8a0a5751a8b543f598c4e74': 'Key 53c34ed1d63dcc7af8a0a5751a8b543f598c4e74 not found in /da5_fast/All.sha1c/commit_83.tch'}

 15%|███████████▌                                                                   | 528/3606 [09:01<52:35,  1.03s/it]

Got Errors {'5f045a35e250b60f462d63f541690d35bbcaa128': 'Key 5f045a35e250b60f462d63f541690d35bbcaa128 not found in /da5_fast/All.sha1c/commit_95.tch'}

 15%|████████████                                                                   | 548/3606 [09:21<52:10,  1.02s/it]

Got Errors {'66d1734c0c2a39deba1a3f8bd318cb3744a5e348': 'Key 66d1734c0c2a39deba1a3f8bd318cb3744a5e348 not found in /da5_fast/All.sha1c/commit_102.tch'}

 16%|████████████▊                                                                  | 583/3606 [09:57<51:34,  1.02s/it]

Got Errors {'73705b90b21c31a6aba699c75e509f0122d17bb1': 'Key 73705b90b21c31a6aba699c75e509f0122d17bb1 not found in /da5_fast/All.sha1c/commit_115.tch'}

 16%|████████████▉                                                                  | 589/3606 [10:03<51:28,  1.02s/it]

Got Errors {'75a5c73ad73c33caa9de84af13e398c8a995bc63': 'Key 75a5c73ad73c33caa9de84af13e398c8a995bc63 not found in /da5_fast/All.sha1c/commit_117.tch'}

 16%|████████████▉                                                                  | 592/3606 [10:06<51:25,  1.02s/it]

Got Errors {'76a951951f9f533f203e4d8d4bcf21a6aa75c70a': 'Key 76a951951f9f533f203e4d8d4bcf21a6aa75c70a not found in /da5_fast/All.sha1c/commit_118.tch'}

 17%|█████████████▏                                                                 | 603/3606 [10:18<51:14,  1.02s/it]

Got Errors {'7a9df4df748c6c010f44728507f6fa8711e00023': 'Key 7a9df4df748c6c010f44728507f6fa8711e00023 not found in /da5_fast/All.sha1c/commit_122.tch'}

 17%|█████████████▎                                                                 | 605/3606 [10:20<51:13,  1.02s/it]

Got Errors {'7bc5f367e8dc4e581f56a8d7ebeb2caee4a60614': 'Key 7bc5f367e8dc4e581f56a8d7ebeb2caee4a60614 not found in /da5_fast/All.sha1c/commit_123.tch'}

 17%|█████████████▋                                                                 | 626/3606 [10:41<50:54,  1.02s/it]

Got Errors {'82ee2e76312313b660bef6ade992c1cb39d964a2': 'Key 82ee2e76312313b660bef6ade992c1cb39d964a2 not found in /da5_fast/All.sha1c/commit_2.tch'}

 18%|█████████████▉                                                                 | 634/3606 [10:49<50:43,  1.02s/it]

Got Errors {'85c3b4796b4827ed5a113564649d64070b8543b2': 'Key 85c3b4796b4827ed5a113564649d64070b8543b2 not found in /da5_fast/All.sha1c/commit_5.tch'}

 19%|███████████████                                                                | 688/3606 [11:45<49:47,  1.02s/it]

Got Errors {'9a4aad7d7a8eba5d339ea849dc4ecdfa4388b967': 'Key 9a4aad7d7a8eba5d339ea849dc4ecdfa4388b967 not found in /da5_fast/All.sha1c/commit_26.tch'}

 22%|█████████████████                                                              | 777/3606 [13:16<48:18,  1.02s/it]

Got Errors {'b9b7b90e655d4a4c98bb4d8c793be1958be7b9fa': 'Key b9b7b90e655d4a4c98bb4d8c793be1958be7b9fa not found in /da5_fast/All.sha1c/commit_57.tch'}

 22%|█████████████████▏                                                             | 786/3606 [13:25<48:09,  1.02s/it]

Got Errors {'bdb10bf4fdff4ad7455943c8691df8bd607e198d': 'Key bdb10bf4fdff4ad7455943c8691df8bd607e198d not found in /da5_fast/All.sha1c/commit_61.tch'}

 23%|█████████████████▉                                                             | 819/3606 [13:59<47:40,  1.03s/it]

Got Errors {'c9707c69b8f5a3e4f8429025485c07a4f477131e': 'Key c9707c69b8f5a3e4f8429025485c07a4f477131e not found in /da5_fast/All.sha1c/commit_73.tch'}

 24%|██████████████████▊                                                            | 857/3606 [14:38<46:57,  1.02s/it]

Got Errors {'d60c09958d38d9860242e6590e2aad1005785a3e': 'Key d60c09958d38d9860242e6590e2aad1005785a3e not found in /da5_fast/All.sha1c/commit_86.tch'}

 24%|███████████████████                                                            | 868/3606 [14:49<46:45,  1.02s/it]

Got Errors {'d9c32ef36b5eda847dc094c32164399fdcf4aedc': 'Key d9c32ef36b5eda847dc094c32164399fdcf4aedc not found in /da5_fast/All.sha1c/commit_89.tch'}

 25%|████████████████████                                                           | 916/3606 [15:38<46:01,  1.03s/it]

Got Errors {'ea96007ca88b8f55e50337ce2a47ba2817d4f422': 'Key ea96007ca88b8f55e50337ce2a47ba2817d4f422 not found in /da5_fast/All.sha1c/commit_106.tch'}

 26%|████████████████████▎                                                          | 928/3606 [15:51<45:43,  1.02s/it]

Got Errors {'eea5853d69224b082cf4ccc9b1cf8b9b768d6eeb': 'Key eea5853d69224b082cf4ccc9b1cf8b9b768d6eeb not found in /da5_fast/All.sha1c/commit_110.tch'}

 26%|████████████████████▎                                                          | 929/3606 [15:52<45:43,  1.03s/it]

Got Errors {'ef12ac402527298e2b3e7e44131471865eede4e2': 'Key ef12ac402527298e2b3e7e44131471865eede4e2 not found in /da5_fast/All.sha1c/commit_111.tch'}

 98%|██████████████████████████████████████████████████████████████████████████▍ | 3532/3606 [1:00:25<01:16,  1.04s/it]

Got Errors {'432d2aa26ae6ff16d7e7b52b8cd9038ce82b13fc': 'Key 432d2aa26ae6ff16d7e7b52b8cd9038ce82b13fc not found in /da5_fast/All.sha1c/commit_67.tch'}

100%|████████████████████████████████████████████████████████████████████████████| 3606/3606 [1:01:41<00:00,  1.03s/it]

,commit,tree,parent,author,author_time,author_tz,committer,committer_time,committer_tz,message,sha1,project
0,00103d05f1291a1acf567cbd3f18cb60355096de,933ca1225f801eccb0ec7d301790399666f6502a,[a580cd78da6fc631d56f4f1158e9df4a05128b09],autodocs <autodocs>,1528883833,+0000,autodocs <autodocs>,1528883833,+0000,build based on 07d0d25\n,00103d05f1291a1acf567cbd3f18cb60355096de,kristofferc_pgfplotsx.jl
1,00205d9769d1eebf71c061df26c48c30badfbd8a,fb61a323692ce355647d468d1951032cf77c6e0e,[e33d254b52f8ebb15e8a779add4b6a2b64f5f4b7],Kristoffer Carlsson <kcarlsson89@gmail.com>,1534505613,+0200,Kristoffer Carlsson <kristoffer.carlsson@chalm...,1534508541,+0200,fixes for the display system\n,00205d9769d1eebf71c061df26c48c30badfbd8a,kristofferc_pgfplotsx.jl

In [4]:
# what does the first record looks like?
# commit  parents
v = commit_data[0]
# commit tree, [parent{s}], [author, unixtime, tz ], [ committer, unixtime, tz ], Commit_message ]
print(v)

{'commit': '00103d05f1291a1acf567cbd3f18cb60355096de', 'tree': '933ca1225f801eccb0ec7d301790399666f6502a', 'parent': ['a580cd78da6fc631d56f4f1158e9df4a05128b09'], 'author': 'autodocs <autodocs>', 'author_time': 1528883833, 'author_tz': '+0000', 'committer': 'autodocs <autodocs>', 'committer_time': 1528883833, 'committer_tz': '+0000', 'message': 'build based on 07d0d25\n'}

In [5]:
# Now that the data is retrieved, save it and commit to your GH fork
# First, we need to flatten info in order to export as csv
# our dataframe will have columns project,'commit, author, time, message'
dfinf = pd.DataFrame(columns=['project', 'commit', 'author', 'time', 'message'])
for k in commit_data:
  row = pd.Series({'project':prj, 'commit': k['commit'], 'author': k['author'], 'time': k['author_time'], 'message':k['message']})
  dfinf = pd.concat([dfinf, row.to_frame().T ], ignore_index=True)

In [6]:
# check if it has the right content
dfinf.head(1)

,project,commit,author,time,message
0,stineb_mct,00103d05f1291a1acf567cbd3f18cb60355096de,autodocs <autodocs>,1528883833,build based on 07d0d25\n

In [7]:
#mode a means append, so you have all your projects in the same file
yournetid='wch356'
dfinf.to_csv(yournetid+'_project_summary.csv', index=False,sep=';', mode='a', header=False)

# Make sure you check in to your fork not just the notebook but also the csv files!!!

# Don't forget to add requested data from github and this notebook
### For each of the 10 projects go to their github repo and get the number of stars, number of forks, and the last commit date
### Report (in your notebook) the number of commits, the number of authors, and max and min time for each project based on WoC commits and also add the info you obtained from github